name: database package

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: rymndhng/release-on-push-action@master
              with:
                bump_version_scheme: minor
            - name: Set up go
              uses: actions/setup-go@v4
              with:
                go-version: '1.23'

            - name: Build
              run: go build -v ./...
            
            - name: Test 
              run: go test -v ./...